services:
  - type: web
    name: simple-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python simple_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
