services:
  - type: web
    name: telegram-bot
    env: python
    runtime: python-3.11.7
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    numInstances: 1
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
